### ISSUE TITLE
aqi value from json waqi api was undefined

### ISSUE THREAD

**Issue by kenwiens** [pawkakol1/worlds-air-quality-index#50] opened 2023-12-22 23:08 UTC
How do I stop getting this warning? I've already removed all stations that have gone completely off line (where all values  are unavailable)

This error originated from a custom integration.

Logger: custom_components.worlds_air_quality_index.sensor
Source: custom_components/worlds_air_quality_index/sensor.py:192
Integration: World's Air Quality Index (documentation, issues)
First occurred: December 19, 2023 at 3:23:59 PM (9212 occurrences)
Last logged: 5:04:51 PM

aqi value from json waqi api was undefined ('-' value)

**Comment by pawkakol1** [comment] 2024-01-15 19:18
Your issue is caused by no AQI value in added by you station 

![image](https://github.com/pawkakol1/worlds-air-quality-index/assets/69692263/d2c4b4ca-dc31-4c39-bb17-989c2cb5d79c)

Could you send me station number? I will be able to verify it

**Comment by pawkakol1** [comment] 2024-03-03 15:43
Due to no answer I close the issue

**Closed as completed by pawkakol1** 2024-03-03 15:43 UTC
